[sdl]
fullscreen=false
fulldouble=false
fullresolution=original
windowresolution=480x272
output=surface
autolock=true
sensitivity=40
waitonerror=true
priority=higher,normal
mapperfile=mapper.txt
usescancodes=true
keyhint=true
irkeybini=pspirkeyb.ini

[dosbox]
language=
machine=vga
captures=capture
memsize=12

[render]
frameskip=2
aspect=false
scaler=none

[cpu]
core=normal
cycles=1500
autocycle=false
mincycles=600
maxcycles=2500
cycleup=500
cycledown=500

[mixer]
nosound=true
rate=11025
blocksize=2048
prebuffer=500

[midi]
mpu401=none
device=none
config=

[sblaster]
sbtype=none

[gus]
gus=false

[speaker]
pcspeaker=false

[joystick]
joysticktype=none
timed=false
autofire=false
swap34=false
buttonwrap=true

[serial]
serial1=disabled
serial2=disabled
serial3=disabled
serial4=disabled

[dos]
xms=true
ems=true
umb=true
keyboardlayout=none

[ipx]
ipx=false

[autoexec]
SYSOPT clock 333
@INPUTMAP analog mouse
@INPUTMAP cross enter
@INPUTMAP circle esc
@INPUTMAP triangle p
@INPUTMAP square m
@INPUTMAP up up
@INPUTMAP down down
@INPUTMAP left left
@INPUTMAP right right
@INPUTMAP ltrigger n
@INPUTMAP rtrigger a
@INPUTMAP start enter
@INPUTMAP select esc
mount c GAMES/TTD
C:
TTDX.EXE
